baseURL = 'https://blog.typesafebrew.dev/'
title = 'Ghostbuster91 personal blog'

theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

enableRobotsTXT = true

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Kasper Kondzielski"
  info = "Software Engineer"
  description = "Ghostbuster91's personal website"
  keywords = "blog,developer,personal,nix,scala"
  avatarurl = "images/avatar.jpg"
  gravatar = "kghost0@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  showReadingTime = false
  showBreadCrumbs = true
  showPostNavLinks = true
  showCodeCopyButtons = true

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/ghostbuster91/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/kkondzielski/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "My talks"
  weight = 2
  url = "talks/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"

[params.assets]
  css = ["css/extended/talks.css", "css/extended/custom.css"]
